apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-deployment
spec:
  selector:
      app: nginx-deployment
  ports:
    - protocol: TCP
      port: 80 # http -> 80
      targetPort: nginx-port
      # targetPort: 80
  # clusterIP: 10.0.171.239
  type: LoadBalancer # external IP